stages:
  - push
  - build
  - deploy

Build felixdoering.com:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: build
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:latest  --cache=true

Sync to GitHub:
  image: registry.sweetwater.cloud/infrastructure/docker-deploy-helper/rsync-ssh
  stage: push
  before_script:
    - echo "$SSH_GITHUB" | tr -d '\r' | ssh-add -
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
  script:
    - git remote add github $REMOTE_REPOSITORY_URL || true
    - git push --force --all github
  rules:
    - if: '$CI_COMMIT_BRANCH'


Deploy felixdoering.com:
  image: registry.sweetwater.cloud/infrastructure/docker-deploy-helper/docker-compose
  stage: deploy
  before_script:
    - echo "$SSH_DEPLOY_KEY" | tr -d '\r' | ssh-add -
  script:
    - remote-connect $TARGET_USER@$TARGET_HOST
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker-compose -f docker-compose.yml pull && docker-compose -f docker-compose.yml up -d
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
