title: Felix Döring
baseurl: ""
url: "felixdoering.com"
email:
  address: mail@felixdoering.com
  gpg:
    path: /assets/gpg/Felix-Döring-BDF33B31.asc
    fprint: EF47 E6C7 B7A2 7022 BB02  3243 3F36 9D08 BDF3 3B31
social:
  twitter: https://twitter.com/Felix_Doering
  github: https://github.com/h4llow3En
  telegram: https://t.me/h4llow3En
  linkedin: https://de.linkedin.com/in/felix-döring-7455a6204
  amusic: https://music.apple.com/profile/h4llow3En
  facebook: https://www.facebook.com/h4ll0w3En
  instagram: https://www.instagram.com/h4llow3en_de

languages: ["en", "de"]
exclude_from_localizations:
  - "assets"
  - "favicon.ico"
  - "robots.txt"
  - "android-chrome-192x192.png"
  - "android-chrome-512x512.png"
  - "apple-touch-icon.png"
  - "browserconfig.xml"
  - "favicon-16x16.png"
  - "favicon-32x32.png"
  - "humans.txt"
  - "mstile-150x150.png"
  - "safari-pinned-tab.svg"
  - "site.webmanifest"

markdown:    kramdown
highlighter: rouge

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

collections:
  posts:
    output: true
    permalink: /blog/:title/
  projects:
    output: true
    permalink: /projects/:title/

assets:
  source_maps: false
  destination: "/assets"
  compression: true
  digest: true
  gzip: true

  compress:
    css: true
    js: uglifier
  plugins:
    autoprefixer:
      browsers:
        - "last 2 versions"
    img:
      vips: {}

plugins:
  - jekyll-multiple-languages-plugin
  - jekyll-assets
  - jekyll-email-protect
