title: Felix Döring
baseurl: ""
url: "https://felixdoering.com"
email:
  address: mail@felixdoering.com
  gpg:
    path: /assets/gpg/Felix-Döring-BDF33B31.asc
    fprint: EF47 E6C7 B7A2 7022 BB02  3243 3F36 9D08 BDF3 3B31
social:
  twitter: https://twitter.com/Felix_Doering
  github: https://github.com/h4llow3En
  telegram: https://t.me/h4llow3En
  linkedin: https://de.linkedin.com/in/felix-döring-7455a6204
  amusic: https://music.apple.com/profile/h4llow3En
  facebook: https://www.facebook.com/h4ll0w3En
  instagram: https://www.instagram.com/h4llow3en_de

timezone: Europe/Berlin

languages:
  - en
  - de

exclude_from_localizations:
  - assets
  - favicon.ico
  - android-chrome-192x192.png
  - android-chrome-512x512.png
  - apple-touch-icon.png
  - favicon-16x16.png
  - favicon-32x32.png
  - mstile-150x150.png
  - safari-pinned-tab.svg
  - site.webmanifest
  - .well-known

include:
  - .well-known

markdown:    kramdown
highlighter: rouge

kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

collections:
  posts:
    output: true
    permalink: /blog/:title/
  projects:
    output: true
    permalink: /projects/:title/
  pages:
    output: true
    permalink: /:title/

assets:
  source_maps: false
  destination: "/assets"
  compression: true
  digest: true
  gzip: true

  caching:
    enabled: true
    path: ".jekyll-cache/assets"
    type: file

  compress:
    css: true
    js: uglifier
  plugins:
    css: { autoprefixer: {}}
    autoprefixer:
      browsers:
        - "last 2 versions"
    img:
      vips: {}

plugins:
  - jekyll-assets
  - jekyll-multiple-languages-plugin
  - jekyll-email-protect
  - liquid_reading_time
  - liquid_pluralize
